// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package link is a generated GoMock package.
package link

import (
	context "context"
	reflect "reflect"

	"go.uber.org/mock/gomock"
)

// MockLinkRepository is a mock of LinkRepository interface.
type MockLinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLinkRepositoryMockRecorder
}

// MockLinkRepositoryMockRecorder is the mock recorder for MockLinkRepository.
type MockLinkRepositoryMockRecorder struct {
	mock *MockLinkRepository
}

// NewMockLinkRepository creates a new mock instance.
func NewMockLinkRepository(ctrl *gomock.Controller) *MockLinkRepository {
	mock := &MockLinkRepository{ctrl: ctrl}
	mock.recorder = &MockLinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkRepository) EXPECT() *MockLinkRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockLinkRepository) Count(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockLinkRepositoryMockRecorder) Count(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockLinkRepository)(nil).Count), ctx)
}

// Create mocks base method.
func (m *MockLinkRepository) Create(ctx context.Context, originalURL, shortName string) (*Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, originalURL, shortName)
	ret0, _ := ret[0].(*Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockLinkRepositoryMockRecorder) Create(ctx, originalURL, shortName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLinkRepository)(nil).Create), ctx, originalURL, shortName)
}

// Delete mocks base method.
func (m *MockLinkRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLinkRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLinkRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockLinkRepository) GetByID(ctx context.Context, id int64) (*Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockLinkRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockLinkRepository)(nil).GetByID), ctx, id)
}

// GetByShortName mocks base method.
func (m *MockLinkRepository) GetByShortName(ctx context.Context, shortName string) (*Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByShortName", ctx, shortName)
	ret0, _ := ret[0].(*Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByShortName indicates an expected call of GetByShortName.
func (mr *MockLinkRepositoryMockRecorder) GetByShortName(ctx, shortName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByShortName", reflect.TypeOf((*MockLinkRepository)(nil).GetByShortName), ctx, shortName)
}

// List mocks base method.
func (m *MockLinkRepository) List(ctx context.Context) ([]Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockLinkRepositoryMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLinkRepository)(nil).List), ctx)
}

// ListPaginated mocks base method.
func (m *MockLinkRepository) ListPaginated(ctx context.Context, limit, offset int32) ([]Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPaginated", ctx, limit, offset)
	ret0, _ := ret[0].([]Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPaginated indicates an expected call of ListPaginated.
func (mr *MockLinkRepositoryMockRecorder) ListPaginated(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPaginated", reflect.TypeOf((*MockLinkRepository)(nil).ListPaginated), ctx, limit, offset)
}

// Update mocks base method.
func (m *MockLinkRepository) Update(ctx context.Context, id int64, originalURL, shortName string) (*Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, originalURL, shortName)
	ret0, _ := ret[0].(*Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockLinkRepositoryMockRecorder) Update(ctx, id, originalURL, shortName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLinkRepository)(nil).Update), ctx, id, originalURL, shortName)
}

// MockVisitRepository is a mock of VisitRepository interface.
type MockVisitRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVisitRepositoryMockRecorder
}

// MockVisitRepositoryMockRecorder is the mock recorder for MockVisitRepository.
type MockVisitRepositoryMockRecorder struct {
	mock *MockVisitRepository
}

// NewMockVisitRepository creates a new mock instance.
func NewMockVisitRepository(ctrl *gomock.Controller) *MockVisitRepository {
	mock := &MockVisitRepository{ctrl: ctrl}
	mock.recorder = &MockVisitRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVisitRepository) EXPECT() *MockVisitRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockVisitRepository) Count(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockVisitRepositoryMockRecorder) Count(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockVisitRepository)(nil).Count), ctx)
}

// Create mocks base method.
func (m *MockVisitRepository) Create(ctx context.Context, visit Visit) (*Visit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, visit)
	ret0, _ := ret[0].(*Visit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockVisitRepositoryMockRecorder) Create(ctx, visit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVisitRepository)(nil).Create), ctx, visit)
}

// Delete mocks base method.
func (m *MockVisitRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVisitRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVisitRepository)(nil).Delete), ctx, id)
}

// ListPaginated mocks base method.
func (m *MockVisitRepository) ListPaginated(ctx context.Context, limit, offset int32) ([]Visit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPaginated", ctx, limit, offset)
	ret0, _ := ret[0].([]Visit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPaginated indicates an expected call of ListPaginated.
func (mr *MockVisitRepositoryMockRecorder) ListPaginated(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPaginated", reflect.TypeOf((*MockVisitRepository)(nil).ListPaginated), ctx, limit, offset)
}
