// Code generated by MockGen. DO NOT EDIT.
// Source: code/internal/usecase/link (interfaces: Service)

// Package mocks is a generated GoMock package.
package link

import (
	link "code/internal/domain/link"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateLink mocks base method.
func (m *MockService) CreateLink(arg0 context.Context, arg1, arg2 string) (*link.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLink", arg0, arg1, arg2)
	ret0, _ := ret[0].(*link.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLink indicates an expected call of CreateLink.
func (mr *MockServiceMockRecorder) CreateLink(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLink", reflect.TypeOf((*MockService)(nil).CreateLink), arg0, arg1, arg2)
}

// DeleteLink mocks base method.
func (m *MockService) DeleteLink(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLink", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLink indicates an expected call of DeleteLink.
func (mr *MockServiceMockRecorder) DeleteLink(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLink", reflect.TypeOf((*MockService)(nil).DeleteLink), arg0, arg1)
}

// GetLink mocks base method.
func (m *MockService) GetLink(arg0 context.Context, arg1 int64) (*link.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLink", arg0, arg1)
	ret0, _ := ret[0].(*link.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLink indicates an expected call of GetLink.
func (mr *MockServiceMockRecorder) GetLink(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLink", reflect.TypeOf((*MockService)(nil).GetLink), arg0, arg1)
}

// ListLinks mocks base method.
func (m *MockService) ListLinks(arg0 context.Context) ([]link.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLinks", arg0)
	ret0, _ := ret[0].([]link.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLinks indicates an expected call of ListLinks.
func (mr *MockServiceMockRecorder) ListLinks(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLinks", reflect.TypeOf((*MockService)(nil).ListLinks), arg0)
}

// UpdateLink mocks base method.
func (m *MockService) UpdateLink(arg0 context.Context, arg1 int64, arg2, arg3 string) (*link.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLink", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*link.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLink indicates an expected call of UpdateLink.
func (mr *MockServiceMockRecorder) UpdateLink(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLink", reflect.TypeOf((*MockService)(nil).UpdateLink), arg0, arg1, arg2, arg3)
}
