// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package link is a generated GoMock package.
package link

import (
	link "code/internal/domain/link"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CountLinks mocks base method.
func (m *MockService) CountLinks(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountLinks", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountLinks indicates an expected call of CountLinks.
func (mr *MockServiceMockRecorder) CountLinks(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountLinks", reflect.TypeOf((*MockService)(nil).CountLinks), ctx)
}

// CreateLink mocks base method.
func (m *MockService) CreateLink(ctx context.Context, originalURL, shortName string) (*link.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLink", ctx, originalURL, shortName)
	ret0, _ := ret[0].(*link.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLink indicates an expected call of CreateLink.
func (mr *MockServiceMockRecorder) CreateLink(ctx, originalURL, shortName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLink", reflect.TypeOf((*MockService)(nil).CreateLink), ctx, originalURL, shortName)
}

// DeleteLink mocks base method.
func (m *MockService) DeleteLink(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLink", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLink indicates an expected call of DeleteLink.
func (mr *MockServiceMockRecorder) DeleteLink(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLink", reflect.TypeOf((*MockService)(nil).DeleteLink), ctx, id)
}

// GetLink mocks base method.
func (m *MockService) GetLink(ctx context.Context, id int64) (*link.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLink", ctx, id)
	ret0, _ := ret[0].(*link.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLink indicates an expected call of GetLink.
func (mr *MockServiceMockRecorder) GetLink(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLink", reflect.TypeOf((*MockService)(nil).GetLink), ctx, id)
}

// ListLinks mocks base method.
func (m *MockService) ListLinks(ctx context.Context) ([]link.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLinks", ctx)
	ret0, _ := ret[0].([]link.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLinks indicates an expected call of ListLinks.
func (mr *MockServiceMockRecorder) ListLinks(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLinks", reflect.TypeOf((*MockService)(nil).ListLinks), ctx)
}

// ListLinksPaginated mocks base method.
func (m *MockService) ListLinksPaginated(ctx context.Context, limit, offset int32) (*ListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLinksPaginated", ctx, limit, offset)
	ret0, _ := ret[0].(*ListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLinksPaginated indicates an expected call of ListLinksPaginated.
func (mr *MockServiceMockRecorder) ListLinksPaginated(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLinksPaginated", reflect.TypeOf((*MockService)(nil).ListLinksPaginated), ctx, limit, offset)
}

// UpdateLink mocks base method.
func (m *MockService) UpdateLink(ctx context.Context, id int64, originalURL, shortName string) (*link.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLink", ctx, id, originalURL, shortName)
	ret0, _ := ret[0].(*link.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLink indicates an expected call of UpdateLink.
func (mr *MockServiceMockRecorder) UpdateLink(ctx, id, originalURL, shortName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLink", reflect.TypeOf((*MockService)(nil).UpdateLink), ctx, id, originalURL, shortName)
}
