// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	ID          int64
	OriginalUrl string
	ShortName   string
	CreatedAt   pgtype.Timestamptz
}
