// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: visits.sql

package sqlc

import (
	"context"
)

const countLinkVisits = `-- name: CountLinkVisits :one
SELECT COUNT(*) FROM link_visits
`

// CountLinkVisits
//
//	SELECT COUNT(*) FROM link_visits
func (q *Queries) CountLinkVisits(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLinkVisits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLinkVisit = `-- name: CreateLinkVisit :one
INSERT INTO link_visits (link_id, ip, user_agent, referer, status)
VALUES ($1, $2, $3, NULLIF($4, ''), $5)
RETURNING id, link_id, ip, user_agent, referer, status, created_at
`

type CreateLinkVisitParams struct {
	LinkID    int64
	Ip        string
	UserAgent string
	Column4   interface{}
	Status    int32
}

// CreateLinkVisit
//
//	INSERT INTO link_visits (link_id, ip, user_agent, referer, status)
//	VALUES ($1, $2, $3, NULLIF($4, ''), $5)
//	RETURNING id, link_id, ip, user_agent, referer, status, created_at
func (q *Queries) CreateLinkVisit(ctx context.Context, arg CreateLinkVisitParams) (LinkVisit, error) {
	row := q.db.QueryRow(ctx, createLinkVisit,
		arg.LinkID,
		arg.Ip,
		arg.UserAgent,
		arg.Column4,
		arg.Status,
	)
	var i LinkVisit
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.Ip,
		&i.UserAgent,
		&i.Referer,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLinkVisit = `-- name: DeleteLinkVisit :execrows
DELETE FROM link_visits
WHERE id = $1
`

// DeleteLinkVisit
//
//	DELETE FROM link_visits
//	WHERE id = $1
func (q *Queries) DeleteLinkVisit(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLinkVisit, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listLinkVisitsPaginated = `-- name: ListLinkVisitsPaginated :many
SELECT id, link_id, ip, user_agent, referer, status, created_at
FROM link_visits
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListLinkVisitsPaginatedParams struct {
	Limit  int32
	Offset int32
}

// ListLinkVisitsPaginated
//
//	SELECT id, link_id, ip, user_agent, referer, status, created_at
//	FROM link_visits
//	ORDER BY created_at DESC
//	LIMIT $1 OFFSET $2
func (q *Queries) ListLinkVisitsPaginated(ctx context.Context, arg ListLinkVisitsPaginatedParams) ([]LinkVisit, error) {
	rows, err := q.db.Query(ctx, listLinkVisitsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkVisit
	for rows.Next() {
		var i LinkVisit
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.Ip,
			&i.UserAgent,
			&i.Referer,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
