-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS links
(
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    original_url TEXT         NOT NULL,
    short_name   VARCHAR(32)  NOT NULL UNIQUE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS links;
-- +goose StatementEnd
