// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package visit is a generated GoMock package.
package visit

import (
	link "code/internal/domain/link"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CountVisits mocks base method.
func (m *MockService) CountVisits(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountVisits", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountVisits indicates an expected call of CountVisits.
func (mr *MockServiceMockRecorder) CountVisits(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountVisits", reflect.TypeOf((*MockService)(nil).CountVisits), ctx)
}

// CreateVisit mocks base method.
func (m *MockService) CreateVisit(ctx context.Context, visit link.Visit) (*link.Visit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVisit", ctx, visit)
	ret0, _ := ret[0].(*link.Visit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVisit indicates an expected call of CreateVisit.
func (mr *MockServiceMockRecorder) CreateVisit(ctx, visit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVisit", reflect.TypeOf((*MockService)(nil).CreateVisit), ctx, visit)
}

// DeleteVisit mocks base method.
func (m *MockService) DeleteVisit(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVisit", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVisit indicates an expected call of DeleteVisit.
func (mr *MockServiceMockRecorder) DeleteVisit(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVisit", reflect.TypeOf((*MockService)(nil).DeleteVisit), ctx, id)
}

// ListVisitsPaginated mocks base method.
func (m *MockService) ListVisitsPaginated(ctx context.Context, limit, offset int32) (*ListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVisitsPaginated", ctx, limit, offset)
	ret0, _ := ret[0].(*ListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVisitsPaginated indicates an expected call of ListVisitsPaginated.
func (mr *MockServiceMockRecorder) ListVisitsPaginated(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVisitsPaginated", reflect.TypeOf((*MockService)(nil).ListVisitsPaginated), ctx, limit, offset)
}
